### ISSUE TITLE
How can I fix this error?

### ISSUE THREAD

**Issue by hoavutinh** [mteodoro/mmutils#12]
c:\Temp\mmdb-convert-master>mmdb-convert.py GeoLite2-City.mmdb > GeoIPCity.dat
Traceback (most recent call last):
  File "C:\Temp\mmdb-convert-master\mmdb-convert.py", line 463, in <module>
    metadata, the_tree, _ = parse_mm_file(content)
  File "C:\Temp\mmdb-convert-master\mmdb-convert.py", line 327, in parse_mm_file
    tree = parse_search_tree(s[:tree_size], mm['record_size'].int_val())
  File "C:\Temp\mmdb-convert-master\mmdb-convert.py", line 123, in parse_search_tree
    left, right = to_leftright(s[p:p+record_bytes])
  File "C:\Temp\mmdb-convert-master\mmdb-convert.py", line 80, in to_int28
    a, b = unpack("!LL", s + b'\x00')
**NameError: name 'unpack' is not defined**

**Comment by meteozond** [comment]
```
from struct import unpack
```
I guess...
