### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ASNUM_EDITION_V6'

### ISSUE THREAD

**Issue by jeffsani** [mteodoro/mmutils#14]
Quick question - Is this error related to my environment, the import file, or something else?  This file does not contain any IPv6 addresses...

root# ./csv2dat.py -w Citrix_mynewdb.dat mmcity myoldcsv.csv
Traceback (most recent call last):
  File "./csv2dat.py", line 270, in <module>
    class ASNv6RadixTree(ASNRadixTree):
  File "./csv2dat.py", line 274, in ASNv6RadixTree
    edition = pygeoip.const.ASNUM_EDITION_V6
AttributeError: 'module' object has no attribute 'ASNUM_EDITION_V6'
[root]#

**Comment by joelw** [comment]
This constant was added in version 0.3.0 of pygeoip. Make sure you have at least this version installed.
